[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shell"
path = "src/shell.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
ansi_term = "0.12.1"
rustyline = "12.0.0"
